// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL9KGCMFdbTeGbtXZ9-AnBpUPRY7wGp4k',
    appId: '1:581103504002:web:8facd97674b83ac218829b',
    messagingSenderId: '581103504002',
    projectId: 'hoshan-42d9f',
    authDomain: 'hoshan-42d9f.firebaseapp.com',
    storageBucket: 'hoshan-42d9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2WRiOSEws1alpLitxX0zsX14rT71aPk',
    appId: '1:581103504002:android:d12a150d3d54570418829b',
    messagingSenderId: '581103504002',
    projectId: 'hoshan-42d9f',
    storageBucket: 'hoshan-42d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAENpjFJ2VeVQEt3_Iud9gfqLvuffb7EUI',
    appId: '1:581103504002:ios:4e51253f750a0fc818829b',
    messagingSenderId: '581103504002',
    projectId: 'hoshan-42d9f',
    storageBucket: 'hoshan-42d9f.appspot.com',
    iosClientId: '581103504002-2e454pgr7fes6b94ptbt82rpfldehedq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoshan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAENpjFJ2VeVQEt3_Iud9gfqLvuffb7EUI',
    appId: '1:581103504002:ios:4e51253f750a0fc818829b',
    messagingSenderId: '581103504002',
    projectId: 'hoshan-42d9f',
    storageBucket: 'hoshan-42d9f.appspot.com',
    iosClientId: '581103504002-2e454pgr7fes6b94ptbt82rpfldehedq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoshan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL9KGCMFdbTeGbtXZ9-AnBpUPRY7wGp4k',
    appId: '1:581103504002:web:084a33707f94511118829b',
    messagingSenderId: '581103504002',
    projectId: 'hoshan-42d9f',
    authDomain: 'hoshan-42d9f.firebaseapp.com',
    storageBucket: 'hoshan-42d9f.appspot.com',
  );

}